# Generated by Django 4.0.2 on 2022-02-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(default='No address given', max_length=200),
        ),
    ]
