# Generated by Django 4.0.2 on 2022-02-02 12:54

from django.db import migrations
import re

def extract_postcode(apps, schema_editor):
    # We can't import the Address model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Address = apps.get_model('addressbook', 'Address')
    for address in Address.objects.all():
        postcodes = re.findall(r"(?<!\d)\d{5}(?!\d)", address.address)
        if len(postcodes) > 0:
            address.postcode = postcodes[0]
        address.save()

class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_address_postcode'),
    ]

    operations = [
        migrations.RunPython(extract_postcode),
    ]
